[package]
name = "masswhois"
version = "0.1.0"
authors = ["B. Blechschmidt <blechschmidt@users.noreply.github.com>"]

[dependencies]
mio = "0.6"
netbuf = "0.4.0"
byteorder = "1.0.0"
bitflags = "0.9.1"
trust-dns = "0.10.2"
indoc = "0.2"
regex = "0.2"
